EXTERN_C_START

typedef struct _DEVICE_CONTEXT
{
	WDFUSBDEVICE UsbDevice;
	ULONG PrivateDeviceData;
} DEVICE_CONTEXT, * PDEVICE_CONTEXT;

WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(DEVICE_CONTEXT, DeviceGetContext)

NTSTATUS
USBUMDF2DriverCreateDevice(
	_Inout_ PWDFDEVICE_INIT DeviceInit
);

EVT_WDF_DEVICE_PREPARE_HARDWARE USBUMDF2DriverEvtDevicePrepareHardware;

EXTERN_C_END
